### ISSUE TITLE
Is it updated for 1.8?

### ISSUE THREAD

**Issue by dinferizovic** [twizmwazin/UndercastClient#1]
All in the title. Also, are there any compiled versions that aren't outdated? I deleted JDK and don't feel like installing it just to compiled this

**Comment by twizmwazin** [comment]
Well, it is sorta updated, although most stuff doesn't work. Check my build server

**Comment by ghost** [comment]
http://ci.twizmwaz.in/job/UndercastClient/

**Comment by twizmwazin** [comment]
For future reference when making issues on any repository, don't ask for compiled versions because you are too lazy to compile it yourself. At least pretend to have tried.
